server:
  servlet:
    context-path: /auth
  port: 20000

spring:
#  security:
#    oauth2:
#      client:
#        registration:
  datasource:
    url: jdbc:mysql://121.40.68.89:33306/springboot?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: ENC(iAOmlnCcnZL6/FR4Rk0EuWc68CIMTxJ7)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 121.40.68.89
    password: ENC(faKI2HCdovKW5aA5JoiJ+a/pNMAJ0YlolXA7dT8hFQSI31hG3bqpQw==)
    timeout: 8000
    port: 6379
  messages:
    basename: messages/messages_zh_CN
    cache-duration: 3600
    encoding: UTF-8
jasypt:
  encryptor:
    password: aba0cbeece9ca5ac39c13055b11fbf51